data:
  perm_path: /qfs/projects/dl_calibration/d3m045/dataset/perm.npy
  poro_path: /qfs/projects/dl_calibration/d3m045/dataset/poro.npy
  conc_path: /qfs/projects/dl_calibration/d3m045/dataset/conc.npy
  train_idx_path: /qfs/projects/dl_calibration/d3m045/dataset/splits/train_idx.npy
  val_idx_path: /qfs/projects/dl_calibration/d3m045/dataset/splits/val_idx.npy
  test_idx_path: /qfs/projects/dl_calibration/d3m045/dataset/splits/test_idx.npy

  pred_length: 20
  input_length: 20
  total_length: 40
  t_keep: 365
  dt: 1

model:
  target: dydiff.dydiff_pflotran.DynamicalLDMForPFLOTRANWithStaticCondition
  params:
    total_length: 40
    input_length: 20
    x_channels: 1
    z_channels: 3
    static_latent_channels: 8

    timesteps: 1000
    beta_schedule: cosine
    linear_start: 0.00085
    linear_end: 0.0120

    gamma_schedule: "cosine-0.5"
    linear_start_gamma: 0.
    linear_end_gamma: 0.

    first_stage_key: "image"
    first_stage_key_prev: "prev"
    cond_stage_key: "cond"
    conditioning_key: "concat-video-mask-1st-static"
    cond_stage_config:
      target: torch.nn.Identity

    validate_kwargs:
      ddim: True
      ddim_steps: 50
      ddim_eta: 0.

    first_stage_config:
      model:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        ckpt_path: null
        monitor: "val/rec_loss"
        embed_dim: 3
        lossconfig:
          target: torch.nn.Identity
        ddconfig:
          double_z: True
          z_channels: 3
          resolution: 40
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult: [1, 2, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0

    unet_config:
      target: sgm.modules.diffusionmodules.video_model.VideoUNet
      params:
        num_video_frames: 0
        in_channels: 0
        out_channels: 0
        model_channels: 64
        attention_resolutions: [4, 2, 1]
        num_res_blocks: 2
        channel_mult: [1, 2, 4, 4]
        num_heads: 4
        transformer_depth: 1
        spatial_transformer_attn_type: softmax
        extra_ff_mix_layer: True
        merge_strategy: learned
        video_kernel_size: [3, 1, 1]

training:
  max_iterations: 200000
  model_attrs:
    learning_rate: 1e-4
  batch_size: 16
  num_workers: 8
  accumulate_grad_batches: 1
  logger:
    save_dir: ../logs/pflotran
    logger_freq: 5000
    checkpoint_freq: 10000

